/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hr.mpac;


import com.formdev.flatlaf.FlatDarculaLaf;
import com.formdev.flatlaf.FlatDarkLaf;
import com.formdev.flatlaf.FlatIntelliJLaf;
import com.formdev.flatlaf.FlatLightLaf;
import hr.algebra.model.RoleTransfer;

import hr.algebra.utilities.MessageUtils;
import hr.mpac.view.AddEntitiesPanel;
import hr.mpac.view.AddJournalPanel;
import hr.mpac.view.AdminPanel;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.JRadioButtonMenuItem;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author majap
 */
public class PhotoJournalManager extends javax.swing.JFrame implements RoleTransfer {
private static final String ADD_JOURNAL = "AddJournal";
    private static final String ADD_ENTITY = "AddEntities";
    private static final String ADMIN_PANEL = "AdminPanel";
    private boolean userRole;
    /**
     * Creates new form PhotoJournalManager
     */
    public PhotoJournalManager() {
        initComponents();
       
         if (!userRole) {
            new UserManagerDialog(this, true).setVisible(true);
        }
       handleLookAndFeel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tpContent = new javax.swing.JTabbedPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        miLogOut = new javax.swing.JMenuItem();
        MenuView = new javax.swing.JMenu();
        menuLF = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Settings");

        miLogOut.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        miLogOut.setText("LogOut");
        miLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miLogOutActionPerformed(evt);
            }
        });
        jMenu1.add(miLogOut);

        jMenuBar1.add(jMenu1);

        MenuView.setText("View");

        menuLF.setText("Look and Feel");
        MenuView.add(menuLF);

        jMenuBar1.add(MenuView);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tpContent, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tpContent, javax.swing.GroupLayout.DEFAULT_SIZE, 677, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void miLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miLogOutActionPerformed
        this.dispose();
    
    UserManagerDialog loginDialog = new UserManagerDialog(this, true);

    loginDialog.setVisible(true);

    this.setVisible(true);
    }//GEN-LAST:event_miLogOutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PhotoJournalManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PhotoJournalManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PhotoJournalManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PhotoJournalManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PhotoJournalManager().setVisible(true);
            }
        });
    }
 private void configurePanels() {
     tpContent.removeAll();
     tpContent.add(ADD_JOURNAL, new AddJournalPanel());
        tpContent.add(ADD_ENTITY, new AddEntitiesPanel());
     if (!userRole) {
       tpContent.add(ADMIN_PANEL, new AdminPanel());
     }
      
        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MenuView;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menuLF;
    private javax.swing.JMenuItem miLogOut;
    private javax.swing.JTabbedPane tpContent;
    // End of variables declaration//GEN-END:variables

    @Override
    public void transferRole(boolean userRole) {
      this.userRole = userRole;
        configurePanels();
    }

    private void handleLookAndFeel() {
       
        ButtonGroup bgLookFeel = new ButtonGroup();
       
      UIManager.LookAndFeelInfo[] flatLafThemes = {
        new UIManager.LookAndFeelInfo("Flat Light", FlatLightLaf.class.getName()),
        new UIManager.LookAndFeelInfo("Flat Dark", FlatDarkLaf.class.getName()),
        new UIManager.LookAndFeelInfo("Flat IntelliJ", FlatIntelliJLaf.class.getName()),
        new UIManager.LookAndFeelInfo("Flat Darcula", FlatDarculaLaf.class.getName())
    };

    for (UIManager.LookAndFeelInfo lf : flatLafThemes) {
        JRadioButtonMenuItem mi = new JRadioButtonMenuItem(lf.getName());
        bgLookFeel.add(mi);
        menuLF.add(mi);
        mi.setSelected(UIManager.getLookAndFeel().getName().equals(lf.getName()));
        mi.addActionListener(e -> {
            try {
                UIManager.setLookAndFeel(lf.getClassName());
                SwingUtilities.updateComponentTreeUI(PhotoJournalManager.this);
            } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
                Logger.getLogger(PhotoJournalManager.class.getName()).log(Level.SEVERE, null, ex);
                MessageUtils.showErrorMessage("Error", "Cannot load look and feel");
            }
        });
    }
    }
}
