/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package hr.mpac;

import hr.algebra.model.RoleTransfer;
import hr.algebra.utilities.MessageUtils;
import hr.mpac.view.LoginPanel;
import hr.mpac.view.RegistrationPanel;

/**
 *
 * @author majap
 */
public class UserManagerDialog extends javax.swing.JDialog {
private static final String LOGIN = "Login";
    private static final String REGISTRATION = "Registration";
    private final RoleTransfer roleTransfer;
     private boolean userLoggedIn;
    /**
     * Creates new form UserManagerDialog
     */
    public UserManagerDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
         roleTransfer = (RoleTransfer) parent;
        initComponents();
        configurePanels();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tpContent = new javax.swing.JTabbedPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        tpContent.setMinimumSize(new java.awt.Dimension(800, 600));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tpContent, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tpContent, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
                       if (!userLoggedIn) {
                   
                   MessageUtils.showErrorMessage
        ("Error", "You have to login!");
                   
                }
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
   
     private void configurePanels() {
         tpContent.add(LOGIN, new LoginPanel(role -> {
            userLoggedIn = true; 
            roleTransfer.transferRole(role);
            dispose();
         }));
        tpContent.add(REGISTRATION, new RegistrationPanel());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane tpContent;
    // End of variables declaration//GEN-END:variables
}
